Feature/community recommendations
hummingbird-me/kitsu-server pull request #193
Opened 2017-07-28 12:03 UTC by cinquemb

2017-07-28 14:26 UTC, NuckChorris requested changes

2017-07-28 14:26 UTC, NuckChorris commented on app/models/community_recommendation.rb
> +  end
Now might be a good time to break this syncing-media-with-triple-column thing into a concern 🤔

2017-07-28 14:26 UTC, NuckChorris commented on app/models/community_recommendation.rb
> +      to: follower_notifications
As with AMAs, you're gonna have to create a new Feed instead and have the notification feeds follow it, since Stream limits us to 100 feeds in the `to` field.

In that case, you probably won't need this method or the corresponding worker either, and `WithActivity` should have you covered.

In future, too, you should be aware that `new` doesn't actually save the activity, it merely generates one.  You need to call `save` on it to actually save

2017-07-28 14:26 UTC, NuckChorris commented on app/models/community_recommendation_follow.rb
> +  belongs_to :community_recommendation_request, required: true
You might be able to save some sanity with:

```ruby
belongs_to :request, required: true, class_name: 'CommunityRecommendationRequest'
```

Which would allow you to do stuff like `where(request: request)` instead 😛

2017-08-02 07:43 UTC, NuckChorris approved these changes

2017-09-14 16:28 UTC, JoshFabian commented
If this is good to go, can it be merged until we're ready to work on front-end, in order to avoid conflicts rebasing later?

2017-09-15 05:29 UTC, cinquemb commented
I dont see why not, i'll rebase and merge it in a bit

2017-09-15 05:44 UTC, merged