[WIP] Modified Activity History Stats
hummingbird-me/kitsu-server pull request #201
Opened 2017-08-04 02:43 UTC by toyhammered

1. Implement Recalculate for Anime/Manga
2. Implement Increment/Decrement

2017-08-04 02:52 UTC, wopian commented on app/models/concerns/stat/activity_history.rb
> +      progress = "((changed_data#>>'{progress,1}')::integer - (changed_data#>>'{progress,0}')::integer)"
😱

2017-08-08 04:33 UTC, toyhammered commented
ready for review @NuckChorris

2017-08-08 04:52 UTC, wopian requested changes

2017-08-08 04:52 UTC, wopian commented on app/models/concerns/stat/activity_history.rb
> +      Hash.new { |h, y| h[y] = Hash.new { |h2, m| h2[m] = Hash.new { |h3, d| h3[d] = {} } } }
![](https://imgur.com/PuZYj6q.gif)

2017-08-08 04:58 UTC, wopian requested changes

2017-08-08 04:58 UTC, wopian commented on app/models/concerns/stat/activity_history.rb
> +      dates.each do |date|
![](http://pa1.narvii.com/5869/c5fe52a95a47bbd0e3b1572209615ab45a937715_hq.gif)

2017-09-27 05:58 UTC, NuckChorris reviewed
Frankly I'm finding this logic really hard to follow.  I know I was the one who suggested trying this structure originally, but would it be better to just do a flat hash of `'2017-08-20' => { progress: 6, time: 138 }`

I had hoped this structure would make logic easier but it seems like I was wrong on that

2017-09-27 05:58 UTC, NuckChorris commented on app/models/concerns/stat/activity_history.rb
> +      'total_progress' => 0
Is there a reason for these not to be nil

2017-09-27 05:58 UTC, NuckChorris commented on app/models/concerns/stat/activity_history.rb
> +      progress = "(#{progress1} - #{progress0})"
How about `progress_old`, `progress_new`, and `progress_diff`

2017-09-27 05:58 UTC, NuckChorris commented on app/models/concerns/stat/activity_history.rb
> +      date_trunc = "date_trunc('day', library_events.created_at)"
How about `creation_date`

2017-09-27 05:58 UTC, NuckChorris commented on app/models/concerns/stat/activity_history.rb
> +      activity_dates = user.library_events.where("changed_data ? 'progress'")
You should add a comment explaining what this is building, what this beast is gonna return

2017-09-27 05:58 UTC, NuckChorris commented on app/models/concerns/stat/activity_history.rb
> +      # not happy about having to use Time.now but I think I have to...
Does `Date.today` not work?

2018-01-09 05:09 UTC, NuckChorris commented
(Integrated into #310)

2018-01-09 05:09 UTC, closed without merging