GraphQL - Add Posts and Comments to User
hummingbird-me/kitsu-server pull request #660
Opened 2020-05-23 19:26 UTC by toyhammered

# What

Add ability to query post/comments and pinned post from a user.

# Why

# Checklist

- [ ] All files pass Rubocop
- [ ] Any complex logic is commented
- [ ] Any new systems have thorough documentation
- [ ] Any user-facing changes are behind a feature flag (or: explain why they can't be)

- [ ] All the tests pass
- [ ] Tests have been added to cover the new code

2020-05-31 20:01 UTC, NuckChorris requested changes

2020-05-31 20:01 UTC, NuckChorris commented on app/graphql/types/comment.rb
> +    method: :user
You don't necessarily want the field to be named just `profile`

You might instead consider something descriptive like `creator`

2020-05-31 20:01 UTC, NuckChorris commented on app/graphql/types/comment.rb
> +    description: 'Users who liked this comment.'
I think this is reasonable to hide the Like object, if we need more advanced shit like multiple types of "likes" we can add it later.  Easier to add than remove!

2020-05-31 20:01 UTC, NuckChorris commented on app/graphql/types/comment.rb
> +      likes.map(&:user)
This is an N+1 problem, you need to use a loader to get the User

2020-05-31 20:01 UTC, NuckChorris commented on app/graphql/types/post.rb
> +  field :profile, Types::Profile,
As above, I think you should be more descriptive here

2020-05-31 20:01 UTC, NuckChorris commented on app/graphql/types/post.rb
> +  field :nsfw, Boolean,
I think graphQL generally puts `is` prefixes on these fields like `isSpoiler` or `isNsfw`

2020-05-31 20:01 UTC, NuckChorris commented on app/graphql/types/post.rb
> +      follows.map(&:user)
Here and a few lines up where you do `likes.map` are both N+1 too!  AssociationLoader only loads `post->likes/post_follows`, you need to layer another AssociationLoader to get `post->likes->user`

2020-05-31 22:39 UTC, toyhammered commented on app/graphql/types/comment.rb
> +    method: :user
Ok, I'll go through all the places I use a profile and change them to make more sense per each context.

2020-06-01 03:07 UTC, toyhammered commented on app/graphql/types/comment.rb
> +    method: :user
Debating between `creator` and `owner` 🤔

2020-06-03 00:16 UTC, wopian commented on app/graphql/types/comment.rb
> +    method: :user
`author`?

2020-07-08 08:41 UTC, NuckChorris approved these changes

2020-07-08 16:13 UTC, wopian approved these changes

2020-07-08 20:35 UTC, merged