Graphql mutations anime
hummingbird-me/kitsu-server pull request #748
Opened 2020-07-25 21:44 UTC by toyhammered

# Checklist

- [ ] All files pass Rubocop
- [ ] Any complex logic is commented
- [ ] Any new systems have thorough documentation
- [ ] Any user-facing changes are behind a feature flag (or: explain why they can't be)

- [ ] All the tests pass
- [ ] Tests have been added to cover the new code

2020-07-27 14:52 UTC, toyhammered commented
dependent on #736 being merged

2020-07-28 14:53 UTC, timw4mail commented
This is to update the anime type library entry?

2020-07-28 15:07 UTC, toyhammered commented
> This is to update the anime type library entry?

No, this is to create, update, delete anime. #736 handles the updates of library entries.

2020-08-02 18:59 UTC, NuckChorris approved these changes

2020-08-02 19:07 UTC, NuckChorris requested changes

2020-08-02 19:07 UTC, NuckChorris commented on app/graphql/mutations/anime/create.rb
> +  end
Retracting my approval on the basis of: I'm pretty sure this won't work

2020-08-02 19:42 UTC, NuckChorris approved these changes
After discussion, seems this will work through Magic™

2020-08-02 19:47 UTC, merged