GraphQL - add basic search for anime and manga titles
hummingbird-me/kitsu-server pull request #749
Opened 2020-07-27 03:06 UTC by toyhammered

# What

Add the basic ability to search for anime/manga through Algolia.

# Checklist

- [ ] All files pass Rubocop
- [ ] Any complex logic is commented
- [ ] Any new systems have thorough documentation
- [ ] Any user-facing changes are behind a feature flag (or: explain why they can't be)

- [ ] All the tests pass
- [ ] Tests have been added to cover the new code

2020-08-02 19:10 UTC, NuckChorris requested changes
This needs to apply auth scopes similar to what `services/algolia_key_service.rb` does

2020-10-03 17:07 UTC, wopian commented
Could searching users be added to this?

2020-10-03 19:53 UTC, toyhammered commented
I'll make a new PR for users I think?

2020-10-03 22:02 UTC, wopian approved these changes

2020-10-04 02:48 UTC, merged