GraphQL - add media streams
hummingbird-me/kitsu-server pull request #768
Opened 2020-08-01 17:33 UTC by toyhammered

2020-08-02 02:53 UTC, toyhammered commented
Need to add a new regions field and then also have a dubs/subs field (we will keep the video sub_language and dub_language, but deprecate) and then just add subs/dubs to them, and these will just be an array.

2020-08-04 13:33 UTC, timw4mail approved these changes

2020-08-08 06:24 UTC, NuckChorris requested changes

2020-08-08 06:24 UTC, NuckChorris commented on app/graphql/types/anime.rb
> +    description: ''
Could you add a description for this?

2020-08-08 06:24 UTC, NuckChorris commented on app/graphql/types/video.rb
> +  description ''
you're missing a bunch of descriptions

2020-08-08 18:20 UTC, toyhammered commented on app/graphql/types/video.rb
> +  description ''
it has WIP for a reason 😭

2020-08-14 21:00 UTC, NuckChorris requested changes

2020-08-14 21:00 UTC, NuckChorris commented on app/graphql/types/video.rb
> +    method: :dub_lang
Please don't add new fields that are deprecated from day one, just leave em off

2020-08-15 03:24 UTC, NuckChorris approved these changes

2020-08-15 18:00 UTC, merged