add more links
hummingbird-me/kitsu-server pull request #79
Opened 2017-03-21 03:46 UTC by CRS-ECHO51

2017-03-21 03:50 UTC, toyhammered commented on spec/factories/profile_link_sites.rb
> +      validate_find 'A(https://)?(?<username>[a-zA-z0-9]+)(.booth.pm)?\z'
should be `\A` and also make sure it is `(https?://)?`, you forgot the `?` after the `s`. Check all the ones you did please.

2017-03-21 03:57 UTC, toyhammered requested changes
Start by correcting all of these and I will check over it again.

2017-03-21 03:57 UTC, toyhammered commented on spec/factories/profile_link_sites.rb
> +      validate_find 'A(https://)?(www.)?(anidb.net/)?(up)?(?<username>[0-9]+)\z'
here

2017-03-21 03:57 UTC, toyhammered commented on spec/factories/profile_link_sites.rb
> +      validate_find 'A(https://)?(www.)?(anilist.co/)?(?<username>[a-zA-Z0-9]+)\z'
here

2017-03-21 03:57 UTC, toyhammered commented on spec/factories/profile_link_sites.rb
> +      validate_find 'A(https://)?(?<username>[a-zA-z0-9]+)(.booth.pm)?\z'
should be `\A` and also make sure it is `(https?://)?`, you forgot the `?` after the `s`. Check all the ones you did please, I have marked them as **here**.

2017-03-21 03:57 UTC, toyhammered commented on spec/factories/profile_link_sites.rb
> +      validate_find 'A(https://)?(www.)?(vndb.org/)?(u)?(?<username>[0-9]+)\z'
here

2017-03-21 03:57 UTC, toyhammered commented on spec/models/profile_link_site_spec.rb
> +            http://www.myanimelist.net/profile/FukuchiChiisaia
I know it doesn't really matter but it should be `https`

2017-03-21 03:57 UTC, toyhammered commented on db/seeds/profile_link_sites.yml
> +  validate_find: 'A(https?://)?(www.)?(pixiv.net/)?(member.php?id=)?(?<username>[0-9]+)\z'
here needs to be changed

2017-03-21 03:57 UTC, toyhammered commented on db/seeds/profile_link_sites.yml
> +  validate_find: 'A(https://)?(?<username>[a-zA-z0-9]+)(.booth.pm)?\z'
here

2017-03-21 03:57 UTC, toyhammered commented on db/seeds/profile_link_sites.yml
> +  validate_find: 'A(https://)?(www.)?(anidb.net/)?(up)?(?<username>[0-9]+)\z'
here

2017-03-21 03:57 UTC, toyhammered commented on db/seeds/profile_link_sites.yml
> +  validate_find: 'A(https://)?(www.)?(anilist.co/)?(?<username>[a-zA-Z0-9]+)\z'
here

2017-03-21 03:57 UTC, toyhammered commented on db/seeds/profile_link_sites.yml
> +  validate_find: 'A(https://)?(www.)?(vndb.org/)?(u)?(?<username>[0-9]+)\z'
here

2017-04-19 00:32 UTC, NuckChorris requested changes
I'm fine with VNDB and Pixiv, if you wanna pare it down to those.  The plan is now to eventually convert this system to something where users can put whatever links they want and then we'll pick an icon for it automatically, and _then_ MAL links are easy.  Until then, I think we'd prefer not giving free advertising 😜

2017-04-19 00:32 UTC, NuckChorris commented on db/seeds/profile_link_sites.yml
> +  validate_replace: 'https://anime-planet.com\users\k<username>'
Honestly I don't really like the thought of giving free advertising to AnimePlanet, AniDB, AniList, or MAL (not that MAL needs it from us lmao)

2017-04-19 00:32 UTC, NuckChorris commented on db/seeds/profile_link_sites.yml
> +  validate_replace: 'https://pixiv.me\k<username>'
Pixiv is highly welcome :+1:

2017-04-19 00:38 UTC, JoshFabian commented on db/seeds/profile_link_sites.yml
> +  validate_replace: 'https://pixiv.me\k<username>'
I would actually prefer we stop adding more links. It's getting incredibly messy. This feature needs refactored.

2017-04-19 01:24 UTC, NuckChorris commented on db/seeds/profile_link_sites.yml
> +  validate_replace: 'https://pixiv.me\k<username>'
Alright then, I'll close this and we can go forward with the refactor instead

2017-04-19 01:24 UTC, closed without merging