Allow linking YouTube channel to account
hummingbird-me/kitsu-server pull request #84
Opened 2017-03-24 05:19 UTC by NuckChorris

Crossposts YouTube videos onto your profile feed

2017-03-24 05:56 UTC, vevix commented
Can you add the new model as a `model_hint` to `LinkedAccountResource` :heart:

2017-03-24 05:58 UTC, NuckChorris commented
Ah, nice catch!

2017-03-24 14:08 UTC, vevix commented on app/models/linked_account/youtube_channel.rb
> +          raise 'Unsubscribe failed' unless subscription.unsubscribe
Shouldn't we also unsubscribe on destroy?

2017-03-24 17:13 UTC, vevix commented
Looks to be missing the policy files.

2017-03-24 17:36 UTC, vevix commented on app/services/youtube_service/client.rb
> +    ).freeze
Looks like the URL here is actually `https://www.googleapis.com/oauth2/v3/tokeninfo`

2017-03-24 17:42 UTC, vevix commented on app/services/youtube_service/client.rb
> +    ).freeze
Url here seems to be `https://www.googleapis.com/youtube/v3/channels` (Ref: https://developers.google.com/youtube/v3/docs/channels/list)

```json
{
    "kind": "youtube#channelListResponse",
    "pageInfo": {
        "totalResults": 1,
        "resultsPerPage": 1
    },
    "items": [{
        "kind": "youtube#channel",
        "id": "UCcacpXYQrVx6ywO0QxW5nNQ"
    }]
}
```

2017-03-26 21:22 UTC, NuckChorris commented
I think that should address everything?

2017-04-02 16:37 UTC, trmcnvn requested changes
:construction:

2017-04-02 16:37 UTC, vevix commented on app/services/youtube_service/client.rb
> +      JSON.parse(res.body)['id'] if res.success?
The response body here is in the following format:

```
{
    "kind": "youtube#channelListResponse",
    "pageInfo": {
        "totalResults": 1,
        "resultsPerPage": 1
    },
    "items": [{
        "kind": "youtube#channel",
        "id": "UCcacpXYQrVx6ywO0QxW5nNQ"
    }]
}
```

2017-04-02 16:37 UTC, vevix commented on app/services/youtube_service/client.rb
> +    def initialize(token, api_key:)
Getting error here that `api_key` is always missing.

2017-04-02 17:30 UTC, NuckChorris commented on app/services/youtube_service/client.rb
> +      JSON.parse(res.body)['id'] if res.success?
In hindsight, I have no clue why I assumed it wouldn't use the standard response format for this 🤔

2017-04-03 17:30 UTC, trmcnvn approved these changes

2017-04-09 06:02 UTC, merged