GraphQL - update media search
hummingbird-me/kitsu-server pull request #860
Opened 2020-10-05 02:30 UTC by toyhammered

# What
This updates all 3 media searches to use the `restrict_searchable_attributes`. 

# Why

# Checklist

- [ ] All files pass Rubocop
- [ ] Any complex logic is commented
- [ ] Any new systems have thorough documentation
- [ ] Any user-facing changes are behind a feature flag (or: explain why they can't be)

- [ ] All the tests pass
- [ ] Tests have been added to cover the new code

2020-10-05 04:09 UTC, toyhammered commented
Need to add pundit scopes.

2020-10-05 05:48 UTC, NuckChorris requested changes

2020-10-05 05:48 UTC, NuckChorris commented on app/graphql/types/query_type.rb
> +      restrict_searchable_attributes: %w[titles abbreviated_titles canonical_title slug]
I don't think we need to search `slug`

2020-10-10 23:28 UTC, NuckChorris approved these changes

2020-10-11 04:29 UTC, merged